version: 0.2

phases:
  install:
    commands:
      - echo Install_NPM
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Build Phase
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm run build
  post_build:
    commands:
      - echo Post Build
